# Patesi — Skill Registry Generator
# Reads SKILL.md frontmatter and generates:
#   1. .atl/skill-registry.md
#   2. Skills section for config.yaml
#   3. Skill trigger table for README.md
#
# Usage: .\scripts\generate-registry.ps1
# Requires: PowerShell 5.1+

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoDir = Split-Path -Parent $ScriptDir
$SkillsDir = Join-Path $RepoDir "skills"

Write-Host "Generating skill registry from SKILL.md frontmatter..." -ForegroundColor Cyan

# Collect all skill directories
$skills = Get-ChildItem -Path $SkillsDir -Directory -Filter "sdet-*" | Sort-Object Name

$registryRows = @()
$configSkills = @()
$tableRows = @()

foreach ($skillDir in $skills) {
    $skillFile = Join-Path $skillDir.FullName "SKILL.md"
    if (-not (Test-Path $skillFile)) {
        Write-Host "  SKIP: $($skillDir.Name) — no SKILL.md" -ForegroundColor Yellow
        continue
    }

    $content = Get-Content -Path $skillFile -Raw

    # Extract frontmatter between --- delimiters
    if ($content -match '(?s)^---\s*\r?\n(.*?)\r?\n---') {
        $frontmatter = $matches[1]
    } else {
        Write-Host "  SKIP: $($skillDir.Name) — no frontmatter" -ForegroundColor Yellow
        continue
    }

    # Extract fields
    $name = ""
    $description = ""
    $trigger = ""

    if ($frontmatter -match '(?m)^name:\s*(.+)$') { $name = $matches[1].Trim() }

    # Extract Trigger line (can be anywhere in frontmatter, often inside multi-line description)
    $lines = $frontmatter -split '\r?\n'
    $triggerLine = $lines | Where-Object { $_ -match 'Trigger:' } | Select-Object -First 1
    if ($triggerLine) {
        $trigger = ($triggerLine -replace '(?i)Trigger:\s*', '').Trim()
    }

    # Extract first meaningful description line
    $descLine = $lines | Where-Object { $_ -match '^\s{2}\S' -and $_ -notmatch 'Trigger:' -and $_ -notmatch '^name:' -and $_ -notmatch '^description:' } | Select-Object -First 1
    if ($descLine) {
        $description = $descLine.Trim()
    } else {
        $description = $trigger
    }

    if (-not $name) { $name = $skillDir.Name }

    $relativePath = "skills/$($skillDir.Name)/SKILL.md"

    # Registry row
    $registryRows += "| ``$name`` | $trigger | project | ``$relativePath`` |"

    # Config.yaml entry
    $configSkills += "  - name: $name"
    $configSkills += "    trigger: $($trigger.ToLower())"

    # README table row
    $shortDesc = $description -replace '^\s*>\s*', ''
    $tableRows += "| ``$name`` | $shortDesc |"

    Write-Host "  OK: $name" -ForegroundColor Green
}

# --- Generate .atl/skill-registry.md ---
$registryContent = @"
# Skill Registry — patesi

<!-- AUTO-GENERATED by scripts/generate-registry.ps1 — DO NOT EDIT MANUALLY -->
<!-- Run: .\scripts\generate-registry.ps1 -->

Last updated: $(Get-Date -Format "yyyy-MM-dd")

## Sources scanned

- skills (project)

## Contract

**Delegator use only.** This registry is an index, not a summary. Any agent that launches subagents reads it to select relevant skills, then passes exact ``SKILL.md`` paths for the subagent to read before work.

``SKILL.md`` remains the source of truth. Do not inject generated summaries or compact rules by default; pass paths so subagents load the full runtime contract and preserve author intent.

## Skills

| Skill | Trigger / description | Scope | Path |
| --- | --- | --- | --- |
$($registryRows -join "`n")

## Loading protocol

1. Match task context and target files against the ``Trigger / description`` column.
2. Pass only the matching ``Path`` values to the subagent under ``## Skills to load before work``.
3. Instruct the subagent to read those exact ``SKILL.md`` files before reading, writing, reviewing, testing, or creating artifacts.
4. If no matching skill exists, proceed without project skill injection and report ``skill_resolution: none``.
"@

$registryPath = Join-Path $RepoDir ".atl\skill-registry.md"
Set-Content -Path $registryPath -Value $registryContent -Encoding UTF8
Write-Host ""
Write-Host "Generated: .atl/skill-registry.md ($($skills.Count) skills)" -ForegroundColor Green

# --- Generate skills section for config.yaml ---
$configSnippet = ($configSkills -join "`n")
Write-Host ""
Write-Host "=== config.yaml skills section (copy into config.yaml) ===" -ForegroundColor Yellow
Write-Host $configSnippet
Write-Host "=== end ===" -ForegroundColor Yellow

# --- Generate README table ---
Write-Host ""
Write-Host "=== README skill table (copy into README.md) ===" -ForegroundColor Yellow
Write-Host "| Skill | Descripción |"
Write-Host "|-------|-------------|"
Write-Host ($tableRows -join "`n")
Write-Host "=== end ===" -ForegroundColor Yellow

Write-Host ""
Write-Host "Done. $($skills.Count) skills processed." -ForegroundColor Cyan
