#!/bin/bash
# Patesi — Skill Registry Generator
# Reads SKILL.md frontmatter and generates:
#   1. .atl/skill-registry.md
#   2. Skills section for config.yaml
#   3. Skill trigger table for README.md
#
# Usage: bash scripts/generate-registry.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
SKILLS_DIR="$REPO_DIR/skills"

echo "Generating skill registry from SKILL.md frontmatter..."

REGISTRY_ROWS=""
CONFIG_SKILLS=""
TABLE_ROWS=""
COUNT=0

for skill_dir in "$SKILLS_DIR"/sdet-*; do
    [ -d "$skill_dir" ] || continue
    skill_file="$skill_dir/SKILL.md"
    skill_name=$(basename "$skill_dir")

    if [ ! -f "$skill_file" ]; then
        echo "  SKIP: $skill_name — no SKILL.md"
        continue
    fi

    # Extract frontmatter
    frontmatter=$(sed -n '/^---$/,/^---$/p' "$skill_file" | sed '1d;$d')

    # Extract name
    name=$(echo "$frontmatter" | grep -m1 '^name:' | sed 's/^name: *//')

    # Extract trigger (search anywhere in frontmatter for Trigger: line)
    trigger=$(echo "$frontmatter" | grep -i 'Trigger:' | head -1 | sed 's/.*Trigger: *//')

    # Extract first description line (indented, not Trigger)
    description=$(echo "$frontmatter" | grep '^  ' | grep -vi 'Trigger:' | head -1 | sed 's/^  *//')

    [ -z "$name" ] && name="$skill_name"

    RELATIVE_PATH="skills/$skill_name/SKILL.md"

    REGISTRY_ROWS="$REGISTRY_ROWS| \`$name\` | $trigger | project | \`$RELATIVE_PATH\` |"
    CONFIG_SKILLS="$CONFIG_SKILLS  - name: $name
    trigger: $(echo "$trigger" | tr '[:upper:]' '[:lower:]')"
    TABLE_ROWS="$TABLE_ROWS| \`$name\` | $(echo "$frontmatter" | grep -m1 '^description:' | sed 's/^description: *>//') |"

    echo "  OK: $name"
    COUNT=$((COUNT + 1))
done

# Generate .atl/skill-registry.md
cat > "$REPO_DIR/.atl/skill-registry.md" << HEREDOC
# Skill Registry — patesi

<!-- AUTO-GENERATED by scripts/generate-registry.sh — DO NOT EDIT MANUALLY -->
<!-- Run: bash scripts/generate-registry.sh -->

Last updated: $(date +%Y-%m-%d)

## Sources scanned

- skills (project)

## Contract

**Delegator use only.** This registry is an index, not a summary. Any agent that launches subagents reads it to select relevant skills, then passes exact \`SKILL.md\` paths for the subagent to read before work.

\`SKILL.md\` remains the source of truth. Do not inject generated summaries or compact rules by default; pass paths so subagents load the full runtime contract and preserve author intent.

## Skills

| Skill | Trigger / description | Scope | Path |
| --- | --- | --- | --- |
$REGISTRY_ROWS

## Loading protocol

1. Match task context and target files against the \`Trigger / description\` column.
2. Pass only the matching \`Path\` values to the subagent under \`## Skills to load before work\`.
3. Instruct the subagent to read those exact \`SKILL.md\` files before reading, writing, reviewing, testing, or creating artifacts.
4. If no matching skill exists, proceed without project skill injection and report \`skill_resolution: none\`.
HEREDOC

echo ""
echo "Generated: .atl/skill-registry.md ($COUNT skills)"
echo ""
echo "=== config.yaml skills section ==="
echo "$CONFIG_SKILLS"
echo "=== end ==="
echo ""
echo "Done. $COUNT skills processed."
